name: provider_architecture
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # TODO(rrousselGit) change to 2.1.0 when merged and deployed
  provider: ^3.1.0
  http: ^0.12.0+2
  functional_widget_annotation:
  json_annotation:

builders:
  functional_widget:
  json_serializable:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
